package Model;
// Generated 09-23-2018 06:43:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private BigDecimal catIdcategoria;
     private String catNombre;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Categoria() {
    }

	
    public Categoria(BigDecimal catIdcategoria, String catNombre) {
        this.catIdcategoria = catIdcategoria;
        this.catNombre = catNombre;
    }
    public Categoria(BigDecimal catIdcategoria, String catNombre, Set<Producto> productos) {
       this.catIdcategoria = catIdcategoria;
       this.catNombre = catNombre;
       this.productos = productos;
    }
   
    public BigDecimal getCatIdcategoria() {
        return this.catIdcategoria;
    }
    
    public void setCatIdcategoria(BigDecimal catIdcategoria) {
        this.catIdcategoria = catIdcategoria;
    }
    public String getCatNombre() {
        return this.catNombre;
    }
    
    public void setCatNombre(String catNombre) {
        this.catNombre = catNombre;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


