package Model;
// Generated 09-23-2018 06:43:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private BigDecimal compraIdcompra;
     private Proveedor proveedor;
     private Usuario usuario;
     private Date compraFecha;
     private Set<Comprobante> comprobantes = new HashSet<Comprobante>(0);
     private Set<DetalleCompra> detalleCompras = new HashSet<DetalleCompra>(0);

    public Compra() {
    }

	
    public Compra(BigDecimal compraIdcompra, Proveedor proveedor, Usuario usuario, Date compraFecha) {
        this.compraIdcompra = compraIdcompra;
        this.proveedor = proveedor;
        this.usuario = usuario;
        this.compraFecha = compraFecha;
    }
    public Compra(BigDecimal compraIdcompra, Proveedor proveedor, Usuario usuario, Date compraFecha, Set<Comprobante> comprobantes, Set<DetalleCompra> detalleCompras) {
       this.compraIdcompra = compraIdcompra;
       this.proveedor = proveedor;
       this.usuario = usuario;
       this.compraFecha = compraFecha;
       this.comprobantes = comprobantes;
       this.detalleCompras = detalleCompras;
    }
   
    public BigDecimal getCompraIdcompra() {
        return this.compraIdcompra;
    }
    
    public void setCompraIdcompra(BigDecimal compraIdcompra) {
        this.compraIdcompra = compraIdcompra;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getCompraFecha() {
        return this.compraFecha;
    }
    
    public void setCompraFecha(Date compraFecha) {
        this.compraFecha = compraFecha;
    }
    public Set<Comprobante> getComprobantes() {
        return this.comprobantes;
    }
    
    public void setComprobantes(Set<Comprobante> comprobantes) {
        this.comprobantes = comprobantes;
    }
    public Set<DetalleCompra> getDetalleCompras() {
        return this.detalleCompras;
    }
    
    public void setDetalleCompras(Set<DetalleCompra> detalleCompras) {
        this.detalleCompras = detalleCompras;
    }




}


