package Model;
// Generated 09-23-2018 06:43:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleFactura generated by hbm2java
 */
public class DetalleFactura  implements java.io.Serializable {


     private BigDecimal detfIddetallefactura;
     private Producto producto;
     private Factura factura;
     private BigDecimal detfCantidad;

    public DetalleFactura() {
        factura = new Factura();
        producto = new Producto();
    }

    public DetalleFactura(BigDecimal detfIddetallefactura, Producto producto, Factura factura, BigDecimal detfCantidad) {
       this.detfIddetallefactura = detfIddetallefactura;
       this.producto = producto;
       this.factura = factura;
       this.detfCantidad = detfCantidad;
    }
   
    public BigDecimal getDetfIddetallefactura() {
        return this.detfIddetallefactura;
    }
    
    public void setDetfIddetallefactura(BigDecimal detfIddetallefactura) {
        this.detfIddetallefactura = detfIddetallefactura;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public BigDecimal getDetfCantidad() {
        return this.detfCantidad;
    }
    
    public void setDetfCantidad(BigDecimal detfCantidad) {
        this.detfCantidad = detfCantidad;
    }

}


