package Model;
// Generated 09-23-2018 06:43:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private BigDecimal factIdfactura;
     private Cliente cliente;
     private Usuario usuario;
     private Date factFecha;
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public Factura() {
        usuario = new Usuario();
        cliente = new Cliente();
    }

	
    public Factura(BigDecimal factIdfactura, Usuario usuario, Date factFecha) {
        this.factIdfactura = factIdfactura;
        this.usuario = usuario;
        this.factFecha = factFecha;
    }
    public Factura(BigDecimal factIdfactura, Cliente cliente, Usuario usuario, Date factFecha, Set<DetalleFactura> detalleFacturas) {
       this.factIdfactura = factIdfactura;
       this.cliente = cliente;
       this.usuario = usuario;
       this.factFecha = factFecha;
       this.detalleFacturas = detalleFacturas;
    }
   
    public BigDecimal getFactIdfactura() {
        return this.factIdfactura;
    }
    
    public void setFactIdfactura(BigDecimal factIdfactura) {
        this.factIdfactura = factIdfactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFactFecha() {
        return this.factFecha;
    }
    
    public void setFactFecha(Date factFecha) {
        this.factFecha = factFecha;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


