package Model;
// Generated 09-23-2018 06:43:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Lote generated by hbm2java
 */
public class Lote  implements java.io.Serializable {


     private BigDecimal lotIdlote;
     private Producto producto;
     private String lotNumero;
     private Date lotFechacaducidad;

    public Lote() {
    }

	
    public Lote(BigDecimal lotIdlote, Producto producto, String lotNumero) {
        this.lotIdlote = lotIdlote;
        this.producto = producto;
        this.lotNumero = lotNumero;
    }
    public Lote(BigDecimal lotIdlote, Producto producto, String lotNumero, Date lotFechacaducidad) {
       this.lotIdlote = lotIdlote;
       this.producto = producto;
       this.lotNumero = lotNumero;
       this.lotFechacaducidad = lotFechacaducidad;
    }
   
    public BigDecimal getLotIdlote() {
        return this.lotIdlote;
    }
    
    public void setLotIdlote(BigDecimal lotIdlote) {
        this.lotIdlote = lotIdlote;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getLotNumero() {
        return this.lotNumero;
    }
    
    public void setLotNumero(String lotNumero) {
        this.lotNumero = lotNumero;
    }
    public Date getLotFechacaducidad() {
        return this.lotFechacaducidad;
    }
    
    public void setLotFechacaducidad(Date lotFechacaducidad) {
        this.lotFechacaducidad = lotFechacaducidad;
    }




}


