package Model;
// Generated 09-23-2018 06:43:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private BigDecimal prodCodproducto;
     private UnidadMedida unidadMedida;
     private Categoria categoria;
     private String prodNombre;
     private String prodDescripcion;
     private BigDecimal prodPrecioUnitario;
     private BigDecimal prodPrecioMayoreo;
     private BigDecimal prodCantMinMayoreo;
     private BigDecimal prodCantidad;
     private BigDecimal prodAlertaCantidad;
     private Set<DetalleCompra> detalleCompras = new HashSet<DetalleCompra>(0);
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);
     private Set<Lote> lotes = new HashSet<Lote>(0);

    public Producto() {
        unidadMedida = new UnidadMedida();
        categoria = new Categoria();
    }

	
    public Producto(BigDecimal prodCodproducto, UnidadMedida unidadMedida, Categoria categoria, String prodNombre, BigDecimal prodPrecioUnitario, BigDecimal prodPrecioMayoreo, BigDecimal prodAlertaCantidad) {
        this.prodCodproducto = prodCodproducto;
        this.unidadMedida = unidadMedida;
        this.categoria = categoria;
        this.prodNombre = prodNombre;
        this.prodPrecioUnitario = prodPrecioUnitario;
        this.prodPrecioMayoreo = prodPrecioMayoreo;
        this.prodAlertaCantidad = prodAlertaCantidad;
    }
    public Producto(BigDecimal prodCodproducto, UnidadMedida unidadMedida, Categoria categoria, String prodNombre, String prodDescripcion, BigDecimal prodPrecioUnitario, BigDecimal prodPrecioMayoreo, BigDecimal prodCantMinMayoreo, BigDecimal prodCantidad, BigDecimal prodAlertaCantidad, Set<DetalleCompra> detalleCompras, Set<DetalleFactura> detalleFacturas, Set<Lote> lotes) {
       this.prodCodproducto = prodCodproducto;
       this.unidadMedida = unidadMedida;
       this.categoria = categoria;
       this.prodNombre = prodNombre;
       this.prodDescripcion = prodDescripcion;
       this.prodPrecioUnitario = prodPrecioUnitario;
       this.prodPrecioMayoreo = prodPrecioMayoreo;
       this.prodCantMinMayoreo = prodCantMinMayoreo;
       this.prodCantidad = prodCantidad;
       this.prodAlertaCantidad = prodAlertaCantidad;
       this.detalleCompras = detalleCompras;
       this.detalleFacturas = detalleFacturas;
       this.lotes = lotes;
    }
   
    public BigDecimal getProdCodproducto() {
        return this.prodCodproducto;
    }
    
    public void setProdCodproducto(BigDecimal prodCodproducto) {
        this.prodCodproducto = prodCodproducto;
    }
    public UnidadMedida getUnidadMedida() {
        return this.unidadMedida;
    }
    
    public void setUnidadMedida(UnidadMedida unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getProdNombre() {
        return this.prodNombre;
    }
    
    public void setProdNombre(String prodNombre) {
        this.prodNombre = prodNombre;
    }
    public String getProdDescripcion() {
        return this.prodDescripcion;
    }
    
    public void setProdDescripcion(String prodDescripcion) {
        this.prodDescripcion = prodDescripcion;
    }
    public BigDecimal getProdPrecioUnitario() {
        return this.prodPrecioUnitario;
    }
    
    public void setProdPrecioUnitario(BigDecimal prodPrecioUnitario) {
        this.prodPrecioUnitario = prodPrecioUnitario;
    }
    public BigDecimal getProdPrecioMayoreo() {
        return this.prodPrecioMayoreo;
    }
    
    public void setProdPrecioMayoreo(BigDecimal prodPrecioMayoreo) {
        this.prodPrecioMayoreo = prodPrecioMayoreo;
    }
    public BigDecimal getProdCantMinMayoreo() {
        return this.prodCantMinMayoreo;
    }
    
    public void setProdCantMinMayoreo(BigDecimal prodCantMinMayoreo) {
        this.prodCantMinMayoreo = prodCantMinMayoreo;
    }
    public BigDecimal getProdCantidad() {
        return this.prodCantidad;
    }
    
    public void setProdCantidad(BigDecimal prodCantidad) {
        this.prodCantidad = prodCantidad;
    }
    public BigDecimal getProdAlertaCantidad() {
        return this.prodAlertaCantidad;
    }
    
    public void setProdAlertaCantidad(BigDecimal prodAlertaCantidad) {
        this.prodAlertaCantidad = prodAlertaCantidad;
    }
    public Set<DetalleCompra> getDetalleCompras() {
        return this.detalleCompras;
    }
    
    public void setDetalleCompras(Set<DetalleCompra> detalleCompras) {
        this.detalleCompras = detalleCompras;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }
    public Set<Lote> getLotes() {
        return this.lotes;
    }
    
    public void setLotes(Set<Lote> lotes) {
        this.lotes = lotes;
    }




}


