package Model;
// Generated 09-23-2018 06:43:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private BigDecimal provIdproveedor;
     private String provNit;
     private String provDui;
     private String provNombre;
     private String provApellido;
     private String provDireccion;
     private String provTelefono;
     private String provEmail;
     private Character provJuridica;
     private BigDecimal provFrecDias;
     private Set<Compra> compras = new HashSet<Compra>(0);

    public Proveedor() {
    }

	
    public Proveedor(BigDecimal provIdproveedor, String provNombre) {
        this.provIdproveedor = provIdproveedor;
        this.provNombre = provNombre;
    }
    public Proveedor(BigDecimal provIdproveedor, String provNit, String provDui, String provNombre, String provApellido, String provDireccion, String provTelefono, String provEmail, Character provJuridica, BigDecimal provFrecDias, Set<Compra> compras) {
       this.provIdproveedor = provIdproveedor;
       this.provNit = provNit;
       this.provDui = provDui;
       this.provNombre = provNombre;
       this.provApellido = provApellido;
       this.provDireccion = provDireccion;
       this.provTelefono = provTelefono;
       this.provEmail = provEmail;
       this.provJuridica = provJuridica;
       this.provFrecDias = provFrecDias;
       this.compras = compras;
    }
   
    public BigDecimal getProvIdproveedor() {
        return this.provIdproveedor;
    }
    
    public void setProvIdproveedor(BigDecimal provIdproveedor) {
        this.provIdproveedor = provIdproveedor;
    }
    public String getProvNit() {
        return this.provNit;
    }
    
    public void setProvNit(String provNit) {
        this.provNit = provNit;
    }
    public String getProvDui() {
        return this.provDui;
    }
    
    public void setProvDui(String provDui) {
        this.provDui = provDui;
    }
    public String getProvNombre() {
        return this.provNombre;
    }
    
    public void setProvNombre(String provNombre) {
        this.provNombre = provNombre;
    }
    public String getProvApellido() {
        return this.provApellido;
    }
    
    public void setProvApellido(String provApellido) {
        this.provApellido = provApellido;
    }
    public String getProvDireccion() {
        return this.provDireccion;
    }
    
    public void setProvDireccion(String provDireccion) {
        this.provDireccion = provDireccion;
    }
    public String getProvTelefono() {
        return this.provTelefono;
    }
    
    public void setProvTelefono(String provTelefono) {
        this.provTelefono = provTelefono;
    }
    public String getProvEmail() {
        return this.provEmail;
    }
    
    public void setProvEmail(String provEmail) {
        this.provEmail = provEmail;
    }
    public Character getProvJuridica() {
        return this.provJuridica;
    }
    
    public void setProvJuridica(Character provJuridica) {
        this.provJuridica = provJuridica;
    }
    public BigDecimal getProvFrecDias() {
        return this.provFrecDias;
    }
    
    public void setProvFrecDias(BigDecimal provFrecDias) {
        this.provFrecDias = provFrecDias;
    }
    public Set<Compra> getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }




}


