package Model;
// Generated 09-23-2018 06:43:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private BigDecimal tusuIdtipousuario;
     private String tusuTipo;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public TipoUsuario() {
    }

	
    public TipoUsuario(BigDecimal tusuIdtipousuario, String tusuTipo) {
        this.tusuIdtipousuario = tusuIdtipousuario;
        this.tusuTipo = tusuTipo;
    }
    public TipoUsuario(BigDecimal tusuIdtipousuario, String tusuTipo, Set<Usuario> usuarios) {
       this.tusuIdtipousuario = tusuIdtipousuario;
       this.tusuTipo = tusuTipo;
       this.usuarios = usuarios;
    }
   
    public BigDecimal getTusuIdtipousuario() {
        return this.tusuIdtipousuario;
    }
    
    public void setTusuIdtipousuario(BigDecimal tusuIdtipousuario) {
        this.tusuIdtipousuario = tusuIdtipousuario;
    }
    public String getTusuTipo() {
        return this.tusuTipo;
    }
    
    public void setTusuTipo(String tusuTipo) {
        this.tusuTipo = tusuTipo;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


