package Model;
// Generated 09-23-2018 06:43:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * UnidadMedida generated by hbm2java
 */
public class UnidadMedida  implements java.io.Serializable {


     private BigDecimal unmIdunidadmedida;
     private String unmUnidad;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public UnidadMedida() {
    }

	
    public UnidadMedida(BigDecimal unmIdunidadmedida, String unmUnidad) {
        this.unmIdunidadmedida = unmIdunidadmedida;
        this.unmUnidad = unmUnidad;
    }
    public UnidadMedida(BigDecimal unmIdunidadmedida, String unmUnidad, Set<Producto> productos) {
       this.unmIdunidadmedida = unmIdunidadmedida;
       this.unmUnidad = unmUnidad;
       this.productos = productos;
    }
   
    public BigDecimal getUnmIdunidadmedida() {
        return this.unmIdunidadmedida;
    }
    
    public void setUnmIdunidadmedida(BigDecimal unmIdunidadmedida) {
        this.unmIdunidadmedida = unmIdunidadmedida;
    }
    public String getUnmUnidad() {
        return this.unmUnidad;
    }
    
    public void setUnmUnidad(String unmUnidad) {
        this.unmUnidad = unmUnidad;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


