package Model;
// Generated 09-23-2018 06:43:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String usuDui;
     private TipoUsuario tipoUsuario;
     private String usuNit;
     private String usuNombre;
     private String usuApellido;
     private String usuDireccion;
     private String usuTelefono;
     private String usuEmail;
     private String usuAlias;
     private String usuContrasena;
     private Set<Factura> facturas = new HashSet<Factura>(0);
     private Set<Compra> compras = new HashSet<Compra>(0);

    public Usuario() {
        tipoUsuario = new TipoUsuario();
    }

	
    public Usuario(String usuDui, TipoUsuario tipoUsuario, String usuNombre, String usuApellido, String usuDireccion, String usuAlias, String usuContrasena) {
        this.usuDui = usuDui;
        this.tipoUsuario = tipoUsuario;
        this.usuNombre = usuNombre;
        this.usuApellido = usuApellido;
        this.usuDireccion = usuDireccion;
        this.usuAlias = usuAlias;
        this.usuContrasena = usuContrasena;
    }
    public Usuario(String usuDui, TipoUsuario tipoUsuario, String usuNit, String usuNombre, String usuApellido, String usuDireccion, String usuTelefono, String usuEmail, String usuAlias, String usuContrasena, Set<Factura> facturas, Set<Compra> compras) {
       this.usuDui = usuDui;
       this.tipoUsuario = tipoUsuario;
       this.usuNit = usuNit;
       this.usuNombre = usuNombre;
       this.usuApellido = usuApellido;
       this.usuDireccion = usuDireccion;
       this.usuTelefono = usuTelefono;
       this.usuEmail = usuEmail;
       this.usuAlias = usuAlias;
       this.usuContrasena = usuContrasena;
       this.facturas = facturas;
       this.compras = compras;
    }
   
    public String getUsuDui() {
        return this.usuDui;
    }
    
    public void setUsuDui(String usuDui) {
        this.usuDui = usuDui;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getUsuNit() {
        return this.usuNit;
    }
    
    public void setUsuNit(String usuNit) {
        this.usuNit = usuNit;
    }
    public String getUsuNombre() {
        return this.usuNombre;
    }
    
    public void setUsuNombre(String usuNombre) {
        this.usuNombre = usuNombre;
    }
    public String getUsuApellido() {
        return this.usuApellido;
    }
    
    public void setUsuApellido(String usuApellido) {
        this.usuApellido = usuApellido;
    }
    public String getUsuDireccion() {
        return this.usuDireccion;
    }
    
    public void setUsuDireccion(String usuDireccion) {
        this.usuDireccion = usuDireccion;
    }
    public String getUsuTelefono() {
        return this.usuTelefono;
    }
    
    public void setUsuTelefono(String usuTelefono) {
        this.usuTelefono = usuTelefono;
    }
    public String getUsuEmail() {
        return this.usuEmail;
    }
    
    public void setUsuEmail(String usuEmail) {
        this.usuEmail = usuEmail;
    }
    public String getUsuAlias() {
        return this.usuAlias;
    }
    
    public void setUsuAlias(String usuAlias) {
        this.usuAlias = usuAlias;
    }
    public String getUsuContrasena() {
        return this.usuContrasena;
    }
    
    public void setUsuContrasena(String usuContrasena) {
        this.usuContrasena = usuContrasena;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }
    public Set<Compra> getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }




}


